INSERT INTO burgers (name)
VALUES ('Krabby Patty'),
       ('Pretty Patty'),
       ('Crying Johnny Patty'),
       ('Double Triple Bossy Deluxe'),
       ('Triple Krabby Supreme'),
       ('King-Size Ultra Krabby Supreme'),
       ('Jelly Patty'),
       ('Krusty Krab Pizza'),
       ('Pipsqueak Patty'),
       ('Monster Krabby Patty'),
       ('Crustless Krabby Patty'),
       ('Flabby Patty'),
       ('Chopper Patty'),
       ('Relish Patty'),
       ('Bubble Patty'),
       ('Secret Patty'),
       ('Emergency Krabby Patty'),
       ('All-Bun Patty'),
       ('Pizza Patty'),
       ('Burrito Patty'),
       ('Hatty Patty'),
       ('Briefy Patty'),
       ('Patty-Free Patty'),
       ('Rainbowger'),
       ('Triple Krabby Patty with five scoops of ice cream');

